--IMPORTANT NOTE !!

--WHEN DECLARING ATTRIBUTES OF A TABLE CHECK IF IT'S REFERED BY A PROCEDURE TO KNOW IT'S TYPE 
--AND IF IT'S A VARCHAR HOW MANY CHARACTERS IT HAS TO BE ACCEPTED BY A PROCEDURE

--DONT FORGET REFERENTIAL INTEGRITY
--DONT RUN ANY SHIT 

CREATE TABLE Product(
serial_number INT IDENTITY,
p_name VARCHAR(20),
price DECIMAL(10,2),
rate DECIMAL(2,2),
color VARCHAR(20), --woat?
image VARCHAR(20), --woat again?
description VARCHAR(100), --is it stated in procs?
category VARCHAR(20),
FOREIGN KEY (order_number) REFERENCES Orders ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (cutsomer_username) REFERENCES Customer ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(vendor_username) REFERENCES Vendor ON DELETE CASCADE ON UPDATE CASCADE,
PRIMARY KEY(serial_number)
);